# Generated by Django 3.2.9 on 2021-12-23 01:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 1, 20, 17, 274924, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.group'),
        ),
    ]
